
select * from Classifications

--insert into Classifications values ('greeting', 1)
--insert into Classifications values ('asking about you', 2)
--insert into Classifications values ('asking about your name', 3)
--insert into Classifications values ('thanking', 4)
--insert into Classifications values ('product', 5)
--insert into Classifications values ('range', 6)

select * From WordClassifications


--insert into WordClassifications values (N'hey', 1)
--insert into WordClassifications values (N'hi', 1)
--insert into WordClassifications values (N'hello', 1)
--insert into WordClassifications values (N'«Â·«', 1)
--insert into WordClassifications values (N'„—Õ»«', 1)
--insert into WordClassifications values (N'«Â·« Ê”Â·«', 1)
--insert into WordClassifications values (N'«·”·«„ ⁄·Ìﬂ„', 1)

--insert into WordClassifications values (N'how are you', 2)
--insert into WordClassifications values (N'how r u', 2)
--insert into WordClassifications values (N'how you going', 2)
--insert into WordClassifications values (N'are you okay', 2)
--insert into WordClassifications values (N'ﬂÌ› Õ«·ﬂ', 2)
--insert into WordClassifications values (N'«ÌÂ «·«Œ»«—', 2)
--insert into WordClassifications values (N'⁄«„· «ÌÂ', 2)
--insert into WordClassifications values (N'«“Ìﬂ', 2)

--insert into WordClassifications values (N'what your name', 3)
--insert into WordClassifications values (N'your name', 3)
--insert into WordClassifications values (N'„« «”„ﬂ', 3)
--insert into WordClassifications values (N'«”„ﬂ', 3)

--insert into WordClassifications values (N'thx', 4)
--insert into WordClassifications values (N'thanks', 4)
--insert into WordClassifications values (N'thank you', 4)
--insert into WordClassifications values (N'thank u', 4)

--insert into WordClassifications values (N'chocolate', 5)
--insert into WordClassifications values (N'‘ÊﬂÊ·« Â', 5)
--insert into WordClassifications values (N'butter', 5)
--insert into WordClassifications values (N'“»œÂ', 5)
--insert into WordClassifications values (N'tea', 5)
--insert into WordClassifications values (N'‘«Ì', 5)
--insert into WordClassifications values (N'tissue', 5)
--insert into WordClassifications values (N'„‰«œÌ·', 5)
--insert into WordClassifications values (N'‘›—« ', 5)
--insert into WordClassifications values (N'razor', 5)
--insert into WordClassifications values (N'Õ»Ê»', 5)
--insert into WordClassifications values (N'beans', 5)
--insert into WordClassifications values (N'rice', 5)
--insert into WordClassifications values (N'«—“', 5)
--insert into WordClassifications values (N'chicken', 5)
--insert into WordClassifications values (N'›—«Œ', 5)
--insert into WordClassifications values (N'Õ·Ê', 5)
--insert into WordClassifications values (N'sweet', 5)
--insert into WordClassifications values (N'dessert', 5)
--insert into WordClassifications values (N'milk', 5)
--insert into WordClassifications values (N'Õ·Ì»', 5)
--insert into WordClassifications values (N'cheese', 5)
--insert into WordClassifications values (N'Ã»‰', 5)
--insert into WordClassifications values (N'·Õ„', 5)
--insert into WordClassifications values (N'meat', 5)

--insert into WordClassifications values (N'range', 6)
--insert into WordClassifications values (N'between', 6)
--insert into WordClassifications values (N'above', 6)
--insert into WordClassifications values (N'higher', 6)
--insert into WordClassifications values (N'lower', 6)
--insert into WordClassifications values (N'below', 6)
--insert into WordClassifications values (N'»Ì‰', 6)
--insert into WordClassifications values (N'›Ì ÕœÊœ', 6)
--insert into WordClassifications values (N'«ﬁ· „‰', 6)
--insert into WordClassifications values (N'«⁄·Ì „‰', 6)

--update WordClassifications set Language = 'ar' where PATINDEX(N'%[√-Ì]%', RTRIM(Word)) > 0
--update WordClassifications set Language = 'en' where Language is null

select * from BotSpeeches

--insert into BotSpeeches values (N'«Â·« Ê”Â·« ﬂÌ› Ì„ﬂ‰‰Ì „”«⁄œ ﬂ', '1')
--insert into BotSpeeches values (N'Hello, How can i help you', '1')
--insert into BotSpeeches values (N'Hello, Hope You Have a Nice Day How can i help you', '1')

--insert into BotSpeeches values (N'»ŒÌ— ﬂÌ› Ì„ﬂ‰‰Ì „”«⁄œ ﬂ', '2')
--insert into BotSpeeches values (N'I am Fine, How Can Help You', '2')

--insert into BotSpeeches values (N'Shhh I cannot Tell You My Name My Creators May Delete Me', '3')
--insert into BotSpeeches values (N'«Œ›÷ ’Ê ﬂ ·« Ì„ﬂ‰‰Ì «Œ»«—ﬂ »«”„ —»„« ÌﬁÊ„ „’‰⁄Ì‰Ì »≈·€«∆Ì', '3')

--insert into BotSpeeches values (N'⁄·Ì «·—Õ» Ê«·”⁄Â «‰« Â‰« ·„”«⁄œ ﬂ', '4')
--insert into BotSpeeches values (N'You are Welcome I am Here Helping You', '3')

--insert into BotSpeeches values (N'Hello Here What You Asking About', '1,5')
--insert into BotSpeeches values (N'«Â·« Ê”Â·« √·Ìﬂ „«  »ÕÀ ⁄‰Â ', '1,5')
--insert into BotSpeeches values (N'I am Great Here What You Asking About', '2,5')
--insert into BotSpeeches values (N'»√›÷· Õ«· √·Ìﬂ „«  »ÕÀ ⁄‰Â', '2,5')

--insert into Products values (NEWID(), N'„Ê· Ê „Ìﬂ” ‘ÊﬂÊ·« Â Ê ﬂ—«„Ì·', 'Molto Mix Chocolate and Caramel', 5)
--insert into Products values (NEWID(), N'„Ì·ﬂ« ‘ÊﬂÊ·« Â «Ê—ÌÊ', 'Milka Chocolate Oreo', 25)
--insert into Products values (NEWID(), N'„Ì„ﬂ” ÿÊ›Ï ‘ÊﬂÊ·« Â', 'Memix Toffe Chocolate', 5)
--insert into Products values (NEWID(), N'«·Â«‰„ ”„‰ »ÿ⁄„ «·“»œÂ', 'Al hanem margarine with butter flavor', 60)
--insert into Products values (NEWID(), N'—Ê «‰« “»œÂ', 'Rotana Butter', 30)
--insert into Products values (NEWID(), N'“»œÂ', 'Butter', 15)
--insert into Products values (NEWID(), N'‘«Ì «Õ„œ «Œ÷—', 'Ahmed Tea Green', 20)
--insert into Products values (NEWID(), N'‘«Ì «Õ„œ', 'Ahmed Tea', 10)
--insert into Products values (NEWID(), N'‘«Ì «·⁄—Ê”Â', 'Al Arosa Tea', 8)
--insert into Products values (NEWID(), N'„‰«œÌ· ‰«⁄„Â', 'Soft Tissue', 5)
--insert into Products values (NEWID(), N'„‰«œÌ· ›«Ì‰', 'Fine Tissue', 6)
--insert into Products values (NEWID(), N'„‰«œÌ· „ÿ»Œ', 'Kitchen Tissue', 7)
--insert into Products values (NEWID(), N'ÃÌ·Ì  3 ‘›—Â', 'Gillette 3 Razors', 5)
--insert into Products values (NEWID(), N'ÃÌ·Ì  2 ‘›—Â', 'Gillette 2 Razors', 2)
--insert into Products values (NEWID(), N'·Ê—œ 2 ‘›—Â', 'Lord 2 Razors', 1)
--insert into Products values (NEWID(), N'⁄œ”', 'lentil', 9)
--insert into Products values (NEWID(), N'›«’Ê·Ì« Œ÷—«¡', 'Green Beans', 15)
--insert into Products values (NEWID(), N'›Ê·', 'Brown Beans', 10)
--insert into Products values (NEWID(), N'«—“ »”„ Ì', 'Basmati rice', 30)
--insert into Products values (NEWID(), N'«—“', 'Rice', 8)
--insert into Products values (NEWID(), N'«—“ „ÿ»ÊŒ', 'Cooked Rice', 20)
--insert into Products values (NEWID(), N'›—«Œ »Ì÷Â', 'White Chickens', 26)
--insert into Products values (NEWID(), N'›—«Œ »·œÌ', 'Local Chickens', 30)
--insert into Products values (NEWID(), N'›—«Œ »«‰ÌÂ', 'Boneless Chickens', 40)
--insert into Products values (NEWID(), N'Õ‰«›Â', 'Knafah', 10)
--insert into Products values (NEWID(), N'Õ·«ÊÂ ÿÕÌ‰ÌÂ', 'halvah', 10)
--insert into Products values (NEWID(), N'·»‰ ﬂ«„· «·œ”„', 'Whole Milk', 10)
--insert into Products values (NEWID(), N'·»‰ Œ«·’ «·œ”„', 'Skim Milk', 10)
--insert into Products values (NEWID(), N'·Õ„ » ·Ê', 'Veal Meat', 10)
--insert into Products values (NEWID(), N'·Õ„ »·œÌ', 'Local Meat', 10)
--insert into Products values (NEWID(), N'·Õ„ «” —«·Ì', 'Australian Meat', 10)

select * from Products